import Image from "next/image";
export const metadata = {
  title: "HPB - Privacy Statement",
  description: "High Performance Board",
};

export default function Privacy() {
  return (
    <section className="mt-32 mb-16 xl:px-12">
      <div className="page-header text-center">Privacy Statement</div>
      <div className="full-container bg-white static">
        <div className="card flex flex-col xl:flex-row items-start p-4 xl:py-20 xl:px-36 gap-4 xl:gap-0">
          <div className="card-content">
            <div className="static-header">Information We Collect:</div>
            <ol>
              <li>
                <strong>Personal Information:</strong>
              </li>
              <ul className="list-disc list-inside">
                <li>
                  When you visit our website, we may collect certain personally
                  identifiable information, such as your name, email address,
                  and any other information you provide voluntarily.
                </li>
              </ul>
              <li>
                <strong>Usage Data:</strong>
              </li>
              <ul className="list-disc list-inside">
                <li>
                  We automatically collect information about how you interact
                  with our website. This may include your IP address, browser
                  type, pages visited, and other usage data.
                </li>
              </ul>
            </ol>
            <div className="static-header">How We Use Your Information:</div>

            <p>We use the collected information for the following purposes:</p>
            <ul className="list-disc list-inside">
              <li>To provide and maintain our website.</li>
              <li>To notify you about changes to our services.</li>
              <li>To respond to your inquiries or requests.</li>
            </ul>
            <div className="static-header">Cookies:</div>
            <p>
              We use cookies and similar tracking technologies to enhance your
              browsing experience. You can set your browser to refuse all
              cookies or to indicate when a cookie is being sent.
            </p>
            <div className="static-header">Third-Party Services:</div>
            <p>
              Our website may contain links to third-party websites or services.
              Please note that we are not responsible for the privacy practices
              of such third parties. We encourage you to review the privacy
              statements of these websites.
            </p>
            <div className="static-header">Security:</div>
            <p>
              We take reasonable steps to protect your personal information.
              However, no method of transmission over the internet or electronic
              storage is 100% secure. Therefore, we cannot guarantee absolute
              security.
            </p>
            <div className="static-header">Your Choices:</div>
            <p>You have the right to:</p>
            <ul className="list-disc list-inside">
              <li>Access, update, or delete your personal information.</li>
              <li>Opt-out of receiving communications from us.</li>
            </ul>
            <div className="static-header">
              Changes to This Privacy Statement:
            </div>
            <p>
              We may update our Privacy Statement from time to time. Any changes
              will be posted on this page, and the effective date will be
              updated.
            </p>
            <div className="static-header">Use of Google Analytics</div>
            <p>
              This website uses Google Analytics, a web analytics service
              provided by Google Inc. (&ldquo;Google&rdquo;). Google Analytics
              uses &ldquo;cookies&rdquo;, text files that are stored on your
              computer and that allow an analysis of your use of the website.
              The information generated by the cookie about your use of this
              website is usually transmitted and stored at a Google server in
              the USA. However, if IP address anonymization is activated on this
              website, your IP address will be shortened by Google beforehand
              within member states of the European Union or in other contracting
              states of the Agreement on the European Economic Area. It is only
              in exceptional cases that the full IP address will be sent to a
              Google server in the US and shortened there. On behalf of the
              operator of this website, Google will use this information to
              evaluate your use of the website, to compile reports on website
              activity, and to provide other services related to website usage
              and internet usage to the website operator.&nbsp;
            </p>
            <p>
              The IP address provided by Google Analytics as part of Google
              Analytics will not be merged with other Google data.
            </p>
            <p>
              This website uses Google Analytics with the extension
              &ldquo;_anonymizeIp()&rdquo;. This allows IP addresses to be
              further processed in a shortened form, thus excluding the
              possibility of personal references. If the data collected about
              you contains a personal reference, this is immediately excluded
              and the personal data is immediately deleted.
            </p>
            <p>
              Google also processes your personal data in the USA. Before you
              give your consent in accordance with Art. 49 para. 1 a GDPR, we
              would like to point out in particular that in the USA there may
              not be an adequate level of data protection without a decision on
              appropriateness and without suitable guarantees, as data
              protection laws do not comply with the provisions of the GDPR and
              in particular the rights of data subjects may not be enforceable.
            </p>
            <p>
              The above will only take place if you give us your consent. The
              legal basis is Art. 6 para. 1 sentence 1 lt. a GDPR
              (&ldquo;Consent&rdquo;). This consent is voluntary. You can refuse
              it without giving reasons and without having to fear any
              disadvantages. You can also revoke this consent at any time with
              future effect here, without having to fear any disadvantages.
            </p>
            <p>
              We use Google Analytics to analyse and regularly improve the use
              of our website. We can use the statistics obtained to improve our
              offer and make it more interesting for you as a user.
            </p>
            <p>
              Third Party Information: Google Dublin, Google Ireland Ltd, Gordon
              House, Barrow Street, Dublin 4, Ireland, Fax: +353 (1) 436 1001,
              Terms of Use:&nbsp;
              <a
                href="http://www.google.com/analytics/terms/de.html"
                data-saferedirecturl="https://www.google.com/url?q=http://www.google.com/analytics/terms/de.html&amp;source=gmail&amp;ust=1705929708114000&amp;usg=AOvVaw0k-gfM_9yqYDRAR0mIfam1"
              >
                www.google.com/analytics/terms/de.html
              </a>
              , Privacy Policy:&nbsp;
              <a
                href="http://www.google.com/intl/de/analytics/learn/privacy.html"
                data-saferedirecturl="https://www.google.com/url?q=http://www.google.com/intl/de/analytics/learn/privacy.html&amp;source=gmail&amp;ust=1705929708114000&amp;usg=AOvVaw1ys3vEAEytNmKmBqiuW45_"
              >
                www.google.com/intl/de/analytics/learn/privacy.html
              </a>
              , and the Privacy Policy:&nbsp;
              <a
                href="http://www.google.de/intl/de/policies/privacy"
                data-saferedirecturl="https://www.google.com/url?q=http://www.google.de/intl/de/policies/privacy&amp;source=gmail&amp;ust=1705929708114000&amp;usg=AOvVaw2uX-6MC7ZqnH3AtgLsbGnj"
              >
                www.google.de/intl/de/policies/privacy
              </a>
              .
            </p>
            <div className="static-header">Contact Us:</div>
            <p>
              If you have any questions or concerns about our Privacy Statement,
              please contact us&nbsp;through the contact form.&nbsp;When you
              contact us by e-mail we will collect the personal information you
              provide (e-mail address, first name, last name and, if applicable,
              your telephone number) to answer your questions. We will delete
              data for these purposes after storage is no longer required, or
              limit the processing if there are statutory retention
              requirements.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
